### ISSUE TITLE
Question: "All" stream

### ISSUE THREAD

**Issue by truegoodwill** [benfoster/odyssey#15]
Hi Ben, 
Quick question, (I might have missed this when browsing your code). Do the events also maintain a global sequence order as they are appended to the table? 

In other words, not just their own position (sequence number) within their own stream, but also their sequence number with respect to the entire table of events? I didn't see it explicitly contained in the event class, but thought perhaps global event ordering is implicitly kept somehow. 

The reason this is important: Views (projections) are often created from multiple streams, and the global order of events is important when building those projections.

Also, I think it's a common use case to want to pull "all" events in the order they were appended to the db. So it's nice to be able to search that from a specific start point using a global event sequence number/id. (Rather than just ordering global events by their timestamp or something)

Thank you, and nice to meet you :)

**Comment by benfoster** [comment]
Hey @truegoodwill, thanks for checking out the repo.

What you're describing reminds me of the `$all` stream in Event Store but there is no such concept (or that of projections) with the Cosmos Change Feed. Each event is globally unique by virtue of the event number and the stream ID (the partition key) but I suspect this isn't really the issue. 

If the concern is checkpointing and the ordering of events within a particular "stream", there are some features of Cosmos that help us. When the change feed processor obtains a lease, it does so for a particular partition range. This ensures that a single consumer will always receive the events in order for a particular stream/aggregate. 

With all that said, in my experience with EDA, I would advise consumers do not rely on ordering, particularly when it spans across the transactional boundaries of multiple consumers. I've experienced out-of-order issues in event consumers that uses Event Store and Kinesis, despite the "guarantees" they offered.

**Comment by truegoodwill** [comment]
Yes, the ordering I was concerned about does span the transactional boundaries of multiple aggregates for the purpose of building strange and exotic views :)

Yes, I am influenced by EventStore.

I feel it can be useful to build projections from multiple streams, and sometimes the ordering of the combined events might affect the projection. Right now, you are challenging me to reconsider my aggregate boundaries :) cheerio
